- src: http://github.com/websoft9dev/role_common
  version: master

- src: http://github.com/websoft9dev/role_cloud
  version: master

- src: http://github.com/websoft9dev/role_node.js
  version: master

- src: http://github.com/websoft9dev/role_nginx
  version: master

- src: http://github.com/websoft9dev/role_mongodb
  version: master

- src: http://github.com/websoft9dev/role_docker
  version: master

- src: http://github.com/websoft9dev/role_docker_adminmongo
  version: master

- src: http://github.com/websoft9dev/role_init_password
  version: master

- src: http://github.com/websoft9dev/role_preend
  version: master

- src: http://github.com/websoft9dev/role_end
