# 核心任务
- name: rocketchat
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common,tags: "role_common"} 
    - { role: role_nodejs, tags: "role_nodejs"}
    - { role: role_nginx, tags: "role_nginx"}     
    - { role: role_mongodb, tags: "role_mongodb"}
    - { role: rocketchat, tags: "rocketchat"} 
    - { role: role_preend, tags: "role_preend" } 
