# 核心任务
- name: rocketchat
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common,tags: "role_common"}
#    - { role: role_cloud,tags: "role_cloud"}    
    - { role: role_nodejs, tags: "role_nodejs"}
    - { role: role_nginx, tags: "role_nginx"}     
    - { role: role_mongodb, tags: "role_mongodb"}
#    - { role: role_docker, tags: "role_docker"}
#    - { role: role_docker_adminmongo, tags: "role_docker_adminmongo"}  
    - { role: rocketchat, tags: "rocketchat"} 
    - { role: role_init_password, tags: "role_init_password" }
    - { role: role_preend, tags: "role_preend" } 
#    - { role: role_end, tags: "role_end" } 
                                     