# install OpenCV by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# prepare
- name: Using npm install inherits and n
  shell: sudo npm install -g inherits n && sudo n 12.14.0

# install rocketchat    
- name: Download rocketchat
  unarchive:
    src: "{{rocketchat_download_url}}"
    dest: /opt
    remote_src: yes

- name:  Install rocketchat
  shell: 
  args:
    cmd: npm install
    chdir: /opt/bundle/programs/server

- name: rename for rocketchat
  shell: mv /opt/bundle  /opt/Rocket.Chat

- name: Creat rocketchat_user & set permiss
  shell: |
    useradd -M rocketchat && sudo usermod -L rocketchat
    chown -R rocketchat:rocketchat /opt/Rocket.Chat

# configure MongoDB
- name: Configure MongoDB
  shell: |
    sed -i "s/^#  engine:/  engine: mmapv1/"  /etc/mongod.conf
    sed -i "s/^#replication:/replication:\n  replSetName: rs01/" /etc/mongod.conf

- name: Start & Enable mongod.service
  service: 
    name: mongod 
    state: started
    enabled: yes

- name: Use mongo shell initiate
  shell: mongo --eval "printjson(rs.initiate())"

# configure the Rocket.Chat service
- name: Copy rocketchat.service file
  template:
    src: rocketchat.service
    dest: '/lib/systemd/system/rocketchat.service'
    
- name: Start & Enable rocketchat.service
  service: 
    name: rocketchat 
    state: started
    enabled: yes

# set soft link, -b cover the exist links
# ln -sb src des
- name: set soft link
  shell: |
    ln -sf /opt/Rocket.Chat/   /data/wwwroot

# Check version,
# must use sudo sh -c to solve the no-root permission
#- block:
#  - name: Check rocketchat Version
#    shell: 


# check service state
- name: Check rocketchat Service
  shell: systemctl status rocketchat | grep Active*
  register: check_rocketchat_service
  notify: check_rocketchat_service
