# install OpenCV by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"



  
   
- name: Download rocketchat
  unarchive:
    src: "{{rocketchat_download_url}}"
    dest: /data
    remote_src: yes

- name:  Install rocketchat
  shell: 
  args:
    cmd: npm install
    chdir: /data/bundle/programs/server

- name: rename for rocketchat
  shell: mv /data/bundle  /data/Rocket.Chat

- name: Creat rocketchat_user & set permiss
  shell: |
     useradd -M rocketchat && sudo usermod -L rocketchat
     chown -R rocketchat:rocketchat /opt/Rocket.Chat